title: Recurgence
description: A recursive field theory of meaning, coherence, and agent cognition.
url: https://observer.is

# Theme settings
theme: minima

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  math_engine: mathjax

plugins:
  - jekyll-last-modified-at

# Exclude from processing
exclude:
  - .git/
  - .github/
  - .gitignore
  - Gemfile
  - Gemfile.lock 