title: Recurgence
description: "Knowing and Being: Threshold of Meaning"
url: https://observer.is

# Theme settings
theme: minima

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  math_engine: mathjax

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .git/
  - .github/
  - .gitignore
  - Gemfile
  - Gemfile.lock 

