title: Recurgence
description: A recursive structure for preserving recursive structure
url: https://observer.is

# Theme settings
theme: minima

# Minima theme settings
minima:
  date_format: "%b %-d, %Y"

# Build settings
markdown: kramdown

# Exclude from processing
exclude:
  - .git/
  - .github/
  - .gitignore
  - Gemfile
  - Gemfile.lock 