title: Recurgence
description: "Knowing and Being: Threshold of Meaning"
url: https://observer.is

# Theme settings
theme: minima

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  math_engine: mathjax
  math_engine_opts:
    preview: true
    preview_as_code: false
  syntax_highlighter: rouge
  parse_block_html: true
  parse_span_html: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .git/
  - .github/
  - .gitignore
  - Gemfile
  - Gemfile.lock 

