title: Recurgence
description: A recursive structure for preserving recursive structure
url: https://observer.is

# Theme settings - using custom minimal theme
theme: null
markdown: kramdown

# Custom styling
sass:
  sass_dir: assets/css
  style: compressed

# Simple structure
permalink: pretty

# Exclude from processing
exclude:
  - .git/
  - .github/
  - .gitignore
  - Gemfile
  - Gemfile.lock 