title: Recurgence
description: A recursive structure for preserving recursive structure
url: https://observer.is

# Theme settings
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

# Just the Docs settings
aux_links:
  "Recurgence on GitHub":
    - "https://github.com/someobserver/recurgence"

# Custom styling
sass:
  sass_dir: assets/css
  style: compressed

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude from processing
exclude:
  - .git/
  - .github/
  - .gitignore
  - Gemfile
  - Gemfile.lock 