title: Recurgence
description: A recursive structure for preserving recursive structure
url: https://observer.is

# Theme settings
theme: minima

# Exclude from processing
exclude:
  - .git/
  - .github/
  - .gitignore
  - Gemfile
  - Gemfile.lock 