title: Recurgence
description: A recursive structure for preserving recursive structure
url: https://observer.is

# Theme settings
theme: minima

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  math_engine: mathjax

# Exclude from processing
exclude:
  - .git/
  - .github/
  - .gitignore
  - Gemfile
  - Gemfile.lock 