title: Recurgence
description: A recursive structure for preserving recursive structure
url: https://observer.is

# Theme settings
theme: minima

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Exclude from processing
exclude:
  - .git/
  - .github/
  - .gitignore
  - Gemfile
  - Gemfile.lock 